
package Vistas;

import Modelo.Alumno;
import Persistencia.alumnoData;
import java.lang.classfile.Superclass;
import java.net.ConnectException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.DataLine;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VistaAlumno extends javax.swing.JInternalFrame {

   DefaultTableModel modelotabla; 

    
    public  VistaAlumno() {
        initComponents();
        String[] titulos = {"DNI","Apellido","nombre","fecha nacimiento","estado"};
        DefaultTableModel nuevoModelo = new DefaultTableModel(null,titulos);
        jtAlumnos.setModel (nuevoModelo);
     
    }
    private alumnoData alum = new alumnoData();
    private Alumno alumnito = new Alumno();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jlGestionAlumnos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlDni = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlNombreAlumno = new javax.swing.JLabel();
        jlFechaNacimiento = new javax.swing.JLabel();
        jlEstadoAlumno = new javax.swing.JLabel();
        jtfDni = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jtfNombreAlumno = new javax.swing.JTextField();
        jtfFechaNacimiento = new javax.swing.JTextField();
        jcbEstadoAlumno = new javax.swing.JComboBox<>();
        jbVerAlumnos = new javax.swing.JButton();
        jbAltaLogicaAlumno = new javax.swing.JButton();
        jbBajaLogicaAlumno = new javax.swing.JButton();
        jbInsertarAlumno = new javax.swing.JButton();
        jbActualizarAlumnos = new javax.swing.JButton();
        jbEliminarAlumnos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtAlumnos = new javax.swing.JTable();

        setClosable(true);

        jlGestionAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlGestionAlumnos.setText("Gestion de Alumnos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlDni.setText("DNI:");

        jlApellido.setText("Apellido:");

        jlNombreAlumno.setText("Nombre:");

        jlFechaNacimiento.setText("Fecha de Nacimiento:");

        jlEstadoAlumno.setText("Estado:");

        jtfDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDniActionPerformed(evt);
            }
        });

        jcbEstadoAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jbVerAlumnos.setText("Ver Alumnos");
        jbVerAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerAlumnosActionPerformed(evt);
            }
        });

        jbAltaLogicaAlumno.setText("Alta Logica");
        jbAltaLogicaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaLogicaAlumnoActionPerformed(evt);
            }
        });

        jbBajaLogicaAlumno.setText("Baja Logica");
        jbBajaLogicaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaLogicaAlumnoActionPerformed(evt);
            }
        });

        jbInsertarAlumno.setText("Insertar");
        jbInsertarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInsertarAlumnoActionPerformed(evt);
            }
        });

        jbActualizarAlumnos.setText("Actualizar");
        jbActualizarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarAlumnosActionPerformed(evt);
            }
        });

        jbEliminarAlumnos.setText("Eliminar");
        jbEliminarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarAlumnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlFechaNacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlDni)
                            .addComponent(jlApellido)
                            .addComponent(jlNombreAlumno))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jtfDni)
                            .addComponent(jtfNombreAlumno)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlEstadoAlumno)
                        .addGap(37, 37, 37)
                        .addComponent(jcbEstadoAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbInsertarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbActualizarAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbEliminarAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbBajaLogicaAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbVerAlumnos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jbAltaLogicaAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDni)
                            .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlApellido)
                            .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbAltaLogicaAlumno)
                            .addComponent(jbInsertarAlumno))))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreAlumno)
                    .addComponent(jtfNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBajaLogicaAlumno)
                    .addComponent(jbActualizarAlumnos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlFechaNacimiento)
                            .addComponent(jtfFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbVerAlumnos)
                            .addComponent(jbEliminarAlumnos))
                        .addGap(8, 8, 8)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEstadoAlumno)
                    .addComponent(jcbEstadoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jtAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dni", "Apellido", "Nombre", "Fecha de nacimiento", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jtAlumnos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jlGestionAlumnos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlGestionAlumnos)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jbVerAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbVerAlumnosActionPerformed

    private void jbInsertarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInsertarAlumnoActionPerformed
       
        String dnistr = jtfDni.getText();
        String apellido = jtfApellido.getText();
        String nombre = jtfNombreAlumno.getText();
        String fechastr = jtfFechaNacimiento.getText();
        String estadofals = jcbEstadoAlumno.getSelectedItem().toString();
        int dni = 0;
        LocalDate fechaNacimiento = null;
        boolean estado = false;
        try {
            dni=Integer.parseInt(dnistr);
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
            fechaNacimiento = LocalDate.now();
            estado = estadofals.equalsIgnoreCase("activo");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Error en la forma de la fecha","Error de conversion",JOptionPane.ERROR_MESSAGE);
            return;
        }

        Alumno nuevoAlumno = new Alumno(dni,apellido,nombre,fechaNacimiento,estado);
        DefaultTableModel modelo = (DefaultTableModel) jtAlumnos.getModel();
        DateTimeFormatter formatoSalida = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        Object[] fila = new Object[]{
        nuevoAlumno.getDni(),
        nuevoAlumno.getApellido(),
        nuevoAlumno.getNombre(),
       nuevoAlumno.getFechaNacimiento().format(formatoSalida),
        nuevoAlumno.getEstadoString(),
        };
                
        modelo.addRow(fila);
    }//GEN-LAST:event_jbInsertarAlumnoActionPerformed
    
  
    
    public void refreshTable(){
     while(modelotabla.getRowCount() > 0){
       modelotabla.getRowCount();
       }
    }
    
    private void jbEliminarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarAlumnosActionPerformed
       int filaSeleccionada = jtAlumnos.getSelectedRow();
       if(filaSeleccionada != -1){
       modelotabla.removeRow(filaSeleccionada);
       }else{JOptionPane.showMessageDialog(this, "seleccione una fila para eliminar");}
    }//GEN-LAST:event_jbEliminarAlumnosActionPerformed
 
    private void jbAltaLogicaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaLogicaAlumnoActionPerformed
        alum.altaLogica(WIDTH);
    JOptionPane.showMessageDialog(this,"alumno dado de alta");
    }//GEN-LAST:event_jbAltaLogicaAlumnoActionPerformed

    private void jbBajaLogicaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaLogicaAlumnoActionPerformed
        alum.bajaLogica(WIDTH);
        JOptionPane.showMessageDialog(this,"alumno dado de baja");
    }//GEN-LAST:event_jbBajaLogicaAlumnoActionPerformed

    private void jbActualizarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarAlumnosActionPerformed
       int id=Integer.parseInt("", WIDTH);
       int dni = Integer.parseInt("",WIDTH);
      int nombre = Integer.parseInt(jtfNombreAlumno.getText());
     
   

    
    }//GEN-LAST:event_jbActualizarAlumnosActionPerformed

    private void jtfDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbActualizarAlumnos;
    private javax.swing.JButton jbAltaLogicaAlumno;
    private javax.swing.JButton jbBajaLogicaAlumno;
    private javax.swing.JButton jbEliminarAlumnos;
    private javax.swing.JButton jbInsertarAlumno;
    private javax.swing.JButton jbVerAlumnos;
    private javax.swing.JComboBox<String> jcbEstadoAlumno;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlDni;
    private javax.swing.JLabel jlEstadoAlumno;
    private javax.swing.JLabel jlFechaNacimiento;
    private javax.swing.JLabel jlGestionAlumnos;
    private javax.swing.JLabel jlNombreAlumno;
    private javax.swing.JTable jtAlumnos;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfDni;
    private javax.swing.JTextField jtfFechaNacimiento;
    private javax.swing.JTextField jtfNombreAlumno;
    // End of variables declaration//GEN-END:variables
}
